import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { clientsClaim } from 'workbox-core';

// Ensure the new SW takes control immediately
self.skipWaiting();
clientsClaim();

// Cleanup outdated caches automatically
cleanupOutdatedCaches();

// Precaching all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ── Roteamento Dinâmico ───────────────────────────────────────────────────

// Map Tiles: Carto Basemaps and AWS Elevation Terrain (Stale-While-Revalidate)
registerRoute(
  ({ url }) => url.href.includes('server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile') ||
    url.href.includes('basemaps.cartocdn.com') ||
    url.href.includes('s3.amazonaws.com/elevation-tiles-prod/terrarium'),
  new StaleWhileRevalidate({
    cacheName: 'agrosmart-maps-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// CDNs (ESM.sh, Tailwind) (Cache First)
registerRoute(
  ({ url }) => url.origin === 'https://cdn.tailwindcss.com' || url.origin === 'https://esm.sh',
  new CacheFirst({
    cacheName: 'agrosmart-cdns-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
      }),
    ],
  })
);

// ── PUSH NOTIFICATIONS ────────────────────────────────────────────────────

self.addEventListener('push', (event) => {
  console.log('[SW] Push Received:', event);

  let data = {
    title: 'OrivaSmart Alerta',
    body: 'Nova atualização do sistema.',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    tag: 'critical-alert'
  };

  if (event.data) {
    try {
      const payload = event.data.json();
      data = { ...data, ...payload };
    } catch (e) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: data.icon,
    badge: data.badge,
    tag: data.tag,
    vibrate: [200, 100, 200],
    data: {
      url: data.url || '/'
    },
    actions: [
      { action: 'open', title: 'Abrir App' },
      { action: 'close', title: 'Fechar' }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification Clicked:', event.notification.tag, event.action);

  event.notification.close();

  const notifData = event.notification.data || {};

  // Geofence Check-in Action
  if (event.action === 'checkin' && notifData.fieldId) {
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
        clients.forEach((client) => {
          client.postMessage({
            type: 'GEOFENCE_CHECKIN',
            fieldId: notifData.fieldId
          });
        });

        if (clients.length === 0 && self.clients.openWindow) {
          return self.clients.openWindow('/?checkin=' + notifData.fieldId);
        }
      })
    );
    return;
  }

  // Generic Notification Click
  if (event.action === 'dismiss') return;

  const urlToOpen = notifData.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Local Geofence Notification
self.addEventListener('message', (event) => {
  if (!event.data || event.data.type !== 'GEOFENCE_ENTRY') return;

  const { field } = event.data;
  if (!field) return;

  console.log('[SW] Geofence entry detected for field:', field.name);

  const options = {
    body: `Bem-vindo a ${field.name}. Quer iniciar o check-in agora?`,
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    image: field.image || undefined,
    tag: 'geofence-checkin-' + field.id,
    renotify: false,
    requireInteraction: true,
    silent: false,
    vibrate: [100, 50, 200, 50, 100],
    data: {
      fieldId: field.id,
      url: '/'
    },
    actions: [
      { action: 'checkin', title: '✅ Iniciar Check-in' },
      { action: 'dismiss', title: '✕ Ignorar' }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(`📍 ${field.name}`, options)
  );
});
